Update continuous-benchmarking-image-size.yml

diff --git a/.github/workflows/continuous-benchmarking-image-size.yml b/.github/workflows/continuous-benchmarking-image-size.yml
--- a/.github/workflows/continuous-benchmarking-image-size.yml
+++ b/.github/workflows/continuous-benchmarking-image-size.yml
@@ -68,6 +68,10 @@ jobs:
         uses: actions/setup-node@v3
         with: 
           node-version: 18
+          
+      - name: Cleanup serverless folder 
+        run: |
+              rm -rf /home/ubuntu/actions-runner/_work/_tool/node/18.20.4/x64/lib/node_modules/serverless   
 
       - name: Install Serverless framework and related plugins
         run: npm install -g serverless@3.38.0
@@ -182,10 +186,6 @@ jobs:
       - name: Cleanup serverless folder 
         run: |
               rm -rf /home/ubuntu/actions-runner/_work/_tool/node/18.20.4/x64/lib/node_modules/serverless   
-              
-      - name: Cleanup serverless folder 
-        run: |
-              rm -rf /home/ubuntu/actions-runner/_work/_tool/node/18.20.4/x64/lib/node_modules/serverless 
 
       - name: Install Serverless framework and related plugins
         run: npm install -g serverless@3.38.0
@@ -477,216 +477,216 @@ jobs:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
-  cold-image-size-50-gcr:
-    name: GCR 50MB image size experiment
-    needs: build_client
-    runs-on: [ self-hosted, gcr ]
-    timeout-minutes: 1200
-    env:
-      working-directory: src
-      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  # cold-image-size-50-gcr:
+  #   name: GCR 50MB image size experiment
+  #   needs: build_client
+  #   runs-on: [ self-hosted, gcr ]
+  #   timeout-minutes: 1200
+  #   env:
+  #     working-directory: src
+  #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #     DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-    steps:
-      - name: "Cleanup build folder"
-        run: |
-          sudo rm -rf ./* || true
-          sudo rm -rf ./.??* || true
+  #   steps:
+  #     - name: "Cleanup build folder"
+  #       run: |
+  #         sudo rm -rf ./* || true
+  #         sudo rm -rf ./.??* || true
 
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-        with:
-          ref: continuous-benchmarking
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: continuous-benchmarking
 
-      - id: auth
-        name: Configure GCR credentials
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCR_CREDENTIALS }}
+  #     - id: auth
+  #       name: Configure GCR credentials
+  #       uses: google-github-actions/auth@v1
+  #       with:
+  #         credentials_json: ${{ secrets.GCR_CREDENTIALS }}
 
-      - name: Set up gcloud
-        uses: google-github-actions/setup-gcloud@v1
-        with:
-          version: ">= 363.0.0"
+  #     - name: Set up gcloud
+  #       uses: google-github-actions/setup-gcloud@v1
+  #       with:
+  #         version: ">= 363.0.0"
 
-      - name: Download client artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: STeLLAR-build
+  #     - name: Download client artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: STeLLAR-build
 
-      - name: Untar client build
-        working-directory: ${{ env.working-directory }}
-        run: tar --strip-components=1 -xvf ../build.tar -C .
+  #     - name: Untar client build
+  #       working-directory: ${{ env.working-directory }}
+  #       run: tar --strip-components=1 -xvf ../build.tar -C .
 
-      - name: GCR Image Size 50MB
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 1440
-          max_attempts: 5
-          retry_wait_seconds: 60
-          command: cd src && ./stellar -c ../continuous-benchmarking/experiments/cold-function-invocations/image-size/cold-image-size-50-gcr.json -db
+  #     - name: GCR Image Size 50MB
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 1440
+  #         max_attempts: 5
+  #         retry_wait_seconds: 60
+  #         command: cd src && ./stellar -c ../continuous-benchmarking/experiments/cold-function-invocations/image-size/cold-image-size-50-gcr.json -db
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: cold-image-size-50-gcr
-          path: ${{ env.working-directory }}/latency-samples
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: cold-image-size-50-gcr
+  #         path: ${{ env.working-directory }}/latency-samples
 
-      - name: Add zero'ed data (Failed experiment)
-        if: ${{ failure() }}
-        env: 
-          DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
-        run: |
-          curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-image-size-50-gcr","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"gcr"}' $DATA_INSERT_URL
+  #     - name: Add zero'ed data (Failed experiment)
+  #       if: ${{ failure() }}
+  #       env: 
+  #         DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
+  #       run: |
+  #         curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-image-size-50-gcr","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"gcr"}' $DATA_INSERT_URL
 
-      - name: Send Slack message using Incoming Webhooks
-        if: ${{ failure() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": "Scheduled experiment (Job status)"
-                  }
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Workflow Name*: ${{ github.workflow }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Name*: ${{ github.job }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Status*: ${{ job.status }} ❌"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "<!channel>"
-                    }
-                  ]
-                }
-              ]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+  #     - name: Send Slack message using Incoming Webhooks
+  #       if: ${{ failure() }}
+  #       uses: slackapi/slack-github-action@v1.24.0
+  #       with:
+  #         payload: |
+  #           {
+  #             "blocks": [
+  #               {
+  #                 "type": "header",
+  #                 "text": {
+  #                   "type": "plain_text",
+  #                   "text": "Scheduled experiment (Job status)"
+  #                 }
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Workflow Name*: ${{ github.workflow }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Name*: ${{ github.job }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Status*: ${{ job.status }} ❌"
+  #                   }
+  #                 ]
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "<!channel>"
+  #                   }
+  #                 ]
+  #               }
+  #             ]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
-  cold-image-size-100-gcr:
-    name: GCR 100MB image size experiment
-    needs: build_client
-    runs-on: [ self-hosted, gcr ]
-    timeout-minutes: 1200
-    env:
-      working-directory: src
-      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
-      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  # cold-image-size-100-gcr:
+  #   name: GCR 100MB image size experiment
+  #   needs: build_client
+  #   runs-on: [ self-hosted, gcr ]
+  #   timeout-minutes: 1200
+  #   env:
+  #     working-directory: src
+  #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #     DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-    steps:
-      - name: "Cleanup build folder"
-        run: |
-          sudo rm -rf ./* || true
-          sudo rm -rf ./.??* || true
+  #   steps:
+  #     - name: "Cleanup build folder"
+  #       run: |
+  #         sudo rm -rf ./* || true
+  #         sudo rm -rf ./.??* || true
 
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-        with:
-          ref: continuous-benchmarking
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: continuous-benchmarking
 
-      - id: auth
-        name: Configure GCR credentials
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCR_CREDENTIALS }}
+  #     - id: auth
+  #       name: Configure GCR credentials
+  #       uses: google-github-actions/auth@v1
+  #       with:
+  #         credentials_json: ${{ secrets.GCR_CREDENTIALS }}
 
-      - name: Set up gcloud
-        uses: google-github-actions/setup-gcloud@v1
-        with:
-          version: ">= 363.0.0"
+  #     - name: Set up gcloud
+  #       uses: google-github-actions/setup-gcloud@v1
+  #       with:
+  #         version: ">= 363.0.0"
 
-      - name: Download client artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: STeLLAR-build
+  #     - name: Download client artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: STeLLAR-build
 
-      - name: Untar client build
-        working-directory: ${{ env.working-directory }}
-        run: tar --strip-components=1 -xvf ../build.tar -C .
+  #     - name: Untar client build
+  #       working-directory: ${{ env.working-directory }}
+  #       run: tar --strip-components=1 -xvf ../build.tar -C .
 
-      - name: GCR Image Size 100MB
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 1440
-          max_attempts: 5
-          retry_wait_seconds: 60
-          command: cd src && ./stellar -c ../continuous-benchmarking/experiments/cold-function-invocations/image-size/cold-image-size-100-gcr.json -db
+  #     - name: GCR Image Size 100MB
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 1440
+  #         max_attempts: 5
+  #         retry_wait_seconds: 60
+  #         command: cd src && ./stellar -c ../continuous-benchmarking/experiments/cold-function-invocations/image-size/cold-image-size-100-gcr.json -db
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: cold-image-size-100-gcr
-          path: ${{ env.working-directory }}/latency-samples
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: cold-image-size-100-gcr
+  #         path: ${{ env.working-directory }}/latency-samples
 
-      - name: Add zero'ed data (Failed experiment)
-        if: ${{ failure() }}
-        env: 
-          DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
-        run: |
-          curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-image-size-100-gcr","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"gcr"}' $DATA_INSERT_URL
+  #     - name: Add zero'ed data (Failed experiment)
+  #       if: ${{ failure() }}
+  #       env: 
+  #         DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
+  #       run: |
+  #         curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-image-size-100-gcr","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"gcr"}' $DATA_INSERT_URL
 
-      - name: Send Slack message using Incoming Webhooks
-        if: ${{ failure() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": "Scheduled experiment (Job status)"
-                  }
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Workflow Name*: ${{ github.workflow }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Name*: ${{ github.job }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Status*: ${{ job.status }} ❌"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "<!channel>"
-                    }
-                  ]
-                }
-              ]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+  #     - name: Send Slack message using Incoming Webhooks
+  #       if: ${{ failure() }}
+  #       uses: slackapi/slack-github-action@v1.24.0
+  #       with:
+  #         payload: |
+  #           {
+  #             "blocks": [
+  #               {
+  #                 "type": "header",
+  #                 "text": {
+  #                   "type": "plain_text",
+  #                   "text": "Scheduled experiment (Job status)"
+  #                 }
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Workflow Name*: ${{ github.workflow }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Name*: ${{ github.job }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Status*: ${{ job.status }} ❌"
+  #                   }
+  #                 ]
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "<!channel>"
+  #                   }
+  #                 ]
+  #               }
+  #             ]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
