[AZURE WARM TEST] Update continuous-benchmarking-baseline.yml

diff --git a/.github/workflows/continuous-benchmarking-baseline.yml b/.github/workflows/continuous-benchmarking-baseline.yml
--- a/.github/workflows/continuous-benchmarking-baseline.yml
+++ b/.github/workflows/continuous-benchmarking-baseline.yml
@@ -703,107 +703,107 @@ jobs:
   #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
-  cold-baseline-cloudflare:
-    name: Cloudflare cold baseline experiment
-    needs: build_client
-    runs-on: [ self-hosted, cloudflare ]
-    timeout-minutes: 1200
-    env:
-      working-directory: src
-      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFARE_API_TOKEN_TEST }}
-    steps:
-      - name: "Cleanup build folder"
-        run: |
-          sudo rm -rf ./* || true
-          sudo rm -rf ./.??* || true
+  # cold-baseline-cloudflare:
+  #   name: Cloudflare cold baseline experiment
+  #   needs: build_client
+  #   runs-on: [ self-hosted, cloudflare ]
+  #   timeout-minutes: 1200
+  #   env:
+  #     working-directory: src
+  #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFARE_API_TOKEN_TEST }}
+  #   steps:
+  #     - name: "Cleanup build folder"
+  #       run: |
+  #         sudo rm -rf ./* || true
+  #         sudo rm -rf ./.??* || true
 
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-        with:
-          ref: continuous-benchmarking
+  #     - name: Check out code into the Go module directory
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: continuous-benchmarking
           
-      - name: Set up Node.js 18
-        uses: actions/setup-node@v3
-        with: 
-          node-version: 18
+  #     - name: Set up Node.js 18
+  #       uses: actions/setup-node@v3
+  #       with: 
+  #         node-version: 18
           
-      - name: Install Cloudflare Wrangler
-        run: npm install -g wrangler
+  #     - name: Install Cloudflare Wrangler
+  #       run: npm install -g wrangler
 
-      - name: Download client artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: STeLLAR-build
+  #     - name: Download client artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: STeLLAR-build
 
-      - name: Untar client build
-        working-directory: ${{ env.working-directory }}
-        run: tar --strip-components=1 -xvf ../build.tar -C .
+  #     - name: Untar client build
+  #       working-directory: ${{ env.working-directory }}
+  #       run: tar --strip-components=1 -xvf ../build.tar -C .
 
-      - name: Cloudflare Cold Function Invocation - Baseline
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 1440
-          max_attempts: 5
-          retry_wait_seconds: 60
-          command: cd src && ./stellar -a 356764711652 -o latency-samples -c ../continuous-benchmarking/experiments/cold-function-invocations/cold-baseline-cloudflare.json -db
+  #     - name: Cloudflare Cold Function Invocation - Baseline
+  #       uses: nick-fields/retry@v2
+  #       with:
+  #         timeout_minutes: 1440
+  #         max_attempts: 5
+  #         retry_wait_seconds: 60
+  #         command: cd src && ./stellar -a 356764711652 -o latency-samples -c ../continuous-benchmarking/experiments/cold-function-invocations/cold-baseline-cloudflare.json -db
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: cold-baseline-cloudflare
-          path: ${{ env.working-directory }}/latency-samples
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: cold-baseline-cloudflare
+  #         path: ${{ env.working-directory }}/latency-samples
 
-      - name: Add zero'ed data (Failed experiment)
-        if: ${{ failure() }}
-        env: 
-          DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
-        run: |
-          curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-baseline-cloudflare","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"cloudflare"}' $DATA_INSERT_URL
+  #     - name: Add zero'ed data (Failed experiment)
+  #       if: ${{ failure() }}
+  #       env: 
+  #         DATA_INSERT_URL: ${{ secrets.DATA_INSERT_URL}}
+  #       run: |
+  #         curl -XPOST -H "Content-type: application/json" -d '{"experiment_type":"cold-baseline-cloudflare","date":"'$(date +%F)'","min":"0","max":"0","median":"0","tail_latency":"0","first_quartile":"0","third_quartile":"0","standard_deviation":"0","payload_size":"0","burst_size":"0","IATType":"0","count":"0","provider":"cloudflare"}' $DATA_INSERT_URL
 
-      - name: Send Slack message using Incoming Webhooks
-        if: ${{ failure() }}
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          payload: |
-            {
-              "blocks": [
-                {
-                  "type": "header",
-                  "text": {
-                    "type": "plain_text",
-                    "text": "Scheduled experiment (Job status)"
-                  }
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Workflow Name*: ${{ github.workflow }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Name*: ${{ github.job }}"
-                    },
-                    {
-                      "type": "mrkdwn",
-                      "text": "*Job Status*: ${{ job.status }} ❌"
-                    }
-                  ]
-                },
-                {
-                  "type": "section",
-                  "fields": [
-                    {
-                      "type": "mrkdwn",
-                      "text": "<!channel>"
-                    }
-                  ]
-                }
-              ]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+  #     - name: Send Slack message using Incoming Webhooks
+  #       if: ${{ failure() }}
+  #       uses: slackapi/slack-github-action@v1.24.0
+  #       with:
+  #         payload: |
+  #           {
+  #             "blocks": [
+  #               {
+  #                 "type": "header",
+  #                 "text": {
+  #                   "type": "plain_text",
+  #                   "text": "Scheduled experiment (Job status)"
+  #                 }
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Workflow Name*: ${{ github.workflow }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Name*: ${{ github.job }}"
+  #                   },
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "*Job Status*: ${{ job.status }} ❌"
+  #                   }
+  #                 ]
+  #               },
+  #               {
+  #                 "type": "section",
+  #                 "fields": [
+  #                   {
+  #                     "type": "mrkdwn",
+  #                     "text": "<!channel>"
+  #                   }
+  #                 ]
+  #               }
+  #             ]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
   # cold-baseline-azure:
   #   name: Azure cold baseline experiment
